severity:
  - low
  - medium
  - high
  - critical

tags:
  - technologies
  - takeovers
  - exposures
  - misconfiguration
  - default-logins
  - exposed-panels
  - cve
  - rce
  - lfi
  - sqli
  - ssrf
  - xss
  - idor
  - auth-bypass
  - file-upload
  - unauth
  - disclosure
  - injection

exclude-tags:
  - dos
  - fuzz

rate-limit: 75
bulk-size: 25
concurrency: 30
timeout: 15
retries: 2

no-interactsh: true
silent: true
jsonl: true
stats: true
stats-interval: 30
